package com.ns.dataloading.entityredis.entity;
// Generated Sep 6, 2017 5:48:29 PM by Hibernate Tools 3.4.0.CR1

import org.springframework.data.redis.core.RedisHash;
import org.springframework.data.redis.core.index.Indexed;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import java.io.Serializable;
import java.math.BigDecimal;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * DsainpDistAddInfo generated by hbm2java
 */
@RedisHash("DSAINP_DistAddInfo")
public class DsainpDistAddInfo implements Serializable {

  private Long id;
   private @Indexed long dactlDistributorctl;
   private  String dapswdPassword;
   private  String daemadEmailaddress;
   private  String daebknBankname;
   private  String dabrnmBranchname;
   private  Long dabrcdBranchcode;
   private  Long daphn1Phonenumber;
   private  Long daphn2Phonenumber;
   private  String dablovBnslimitoverride;
   private  String dafut1Vippricing;
   private  String dafut225ccoverride;
   private  String dauserChangeuser;
   private  String dapidChgprogramid;
   private @Indexed String daupdtChangedate;
   private @Indexed String dauptmChangetime;
   private String darctpBanktypecode;
   private  String datrnsBankrtgtransit;
   private  String daactBankacct;
   private String daswftSwiftcode;
   private  String daprenPrenotecode;
   private  String dacksvChkgorsvgsacct;
   private  String dadusrDirdepchguser;
   private  String dadpidDirdepchgpgmid;
   private  String dadudtDirdepchgdate;
   private  String dadutmDirdepchgtime;
   private  String daohcoOverridinghomecountry;
   private  String dawebrWebrecap;
   private  String dadbdtDistbirthdate;
   private  String dasbdtSpoubirthdate;
   private  String damstsMartialstatus;
   private String dalspkLanguagespoken;
   private  Long daatrAppltransactionid;
   private @Indexed String dandpfNdppricingyn;
   private  BigDecimal dabalfBalancefactor;
   private  BigDecimal dafut3Futureuse3;
   private  String dafut4Futureuse4;
   private  String dafut5Futureuse5;
   private String dafut6Futureuse6;
   private String danltrNewletteronweb;
   private String dapipaPersonalinfoprotectionact;
   private String dapyinPaymentinstrument;
   private @Indexed String daoptiOptInReq;
   private @Indexed String daoptfOptInFlag;
   private @Indexed String daopdtOptInDate;
   private  String dascemSpnContbyEml;
   private String dascphSpnContbyPhn;
   private String dadavfAdrVerfdFlag;
   private  BigDecimal dadlatAdrLatitude;
   private  BigDecimal dadlntAdrLongitude;

    public DsainpDistAddInfo() {
    }

    public DsainpDistAddInfo(long dactlDistributorctl, String dapswdPassword, String daemadEmailaddress) {
        this.dactlDistributorctl = dactlDistributorctl;
        this.dapswdPassword = dapswdPassword;
        this.daemadEmailaddress = daemadEmailaddress;
    }

    public DsainpDistAddInfo(long dactlDistributorctl, String dapswdPassword, String daemadEmailaddress,
                             String daebknBankname, String dabrnmBranchname, Long dabrcdBranchcode, Long daphn1Phonenumber,
                             Long daphn2Phonenumber, String dablovBnslimitoverride, String dafut1Vippricing, String dafut225ccoverride,
                             String dauserChangeuser, String dapidChgprogramid, String daupdtChangedate, String dauptmChangetime,
                             String darctpBanktypecode, String datrnsBankrtgtransit, String daactBankacct, String daswftSwiftcode,
                             String daprenPrenotecode, String dacksvChkgorsvgsacct, String dadusrDirdepchguser,
                             String dadpidDirdepchgpgmid, String dadudtDirdepchgdate, String dadutmDirdepchgtime,
                             String daohcoOverridinghomecountry, String dawebrWebrecap, String dadbdtDistbirthdate,
                             String dasbdtSpoubirthdate, String damstsMartialstatus, String dalspkLanguagespoken,
                             Long daatrAppltransactionid, String dandpfNdppricingyn, BigDecimal dabalfBalancefactor,
                             BigDecimal dafut3Futureuse3, String dafut4Futureuse4, String dafut5Futureuse5, String dafut6Futureuse6,
                             String danltrNewletteronweb, String dapipaPersonalinfoprotectionact, String dapyinPaymentinstrument,String daoptiOptInReq,
                             String daoptfOptInFlag,String daopdtOptInDate,String dascemSpnContbyEml,String dascphSpnContbyPhn,String dadavfAdrVerfdFlag,
                             BigDecimal dadlatAdrLatitude,BigDecimal dadlntAdrLongitude) {
        this.dactlDistributorctl = dactlDistributorctl;
        this.dapswdPassword = dapswdPassword;
        this.daemadEmailaddress = daemadEmailaddress;
        this.daebknBankname = daebknBankname;
        this.dabrnmBranchname = dabrnmBranchname;
        this.dabrcdBranchcode = dabrcdBranchcode;
        this.daphn1Phonenumber = daphn1Phonenumber;
        this.daphn2Phonenumber = daphn2Phonenumber;
        this.dablovBnslimitoverride = dablovBnslimitoverride;
        this.dafut1Vippricing = dafut1Vippricing;
        this.dafut225ccoverride = dafut225ccoverride;
        this.dauserChangeuser = dauserChangeuser;
        this.dapidChgprogramid = dapidChgprogramid;
        this.daupdtChangedate = daupdtChangedate;
        this.dauptmChangetime = dauptmChangetime;
        this.darctpBanktypecode = darctpBanktypecode;
        this.datrnsBankrtgtransit = datrnsBankrtgtransit;
        this.daactBankacct = daactBankacct;
        this.daswftSwiftcode = daswftSwiftcode;
        this.daprenPrenotecode = daprenPrenotecode;
        this.dacksvChkgorsvgsacct = dacksvChkgorsvgsacct;
        this.dadusrDirdepchguser = dadusrDirdepchguser;
        this.dadpidDirdepchgpgmid = dadpidDirdepchgpgmid;
        this.dadudtDirdepchgdate = dadudtDirdepchgdate;
        this.dadutmDirdepchgtime = dadutmDirdepchgtime;
        this.daohcoOverridinghomecountry = daohcoOverridinghomecountry;
        this.dawebrWebrecap = dawebrWebrecap;
        this.dadbdtDistbirthdate = dadbdtDistbirthdate;
        this.dasbdtSpoubirthdate = dasbdtSpoubirthdate;
        this.damstsMartialstatus = damstsMartialstatus;
        this.dalspkLanguagespoken = dalspkLanguagespoken;
        this.daatrAppltransactionid = daatrAppltransactionid;
        this.dandpfNdppricingyn = dandpfNdppricingyn;
        this.dabalfBalancefactor = dabalfBalancefactor;
        this.dafut3Futureuse3 = dafut3Futureuse3;
        this.dafut4Futureuse4 = dafut4Futureuse4;
        this.dafut5Futureuse5 = dafut5Futureuse5;
        this.dafut6Futureuse6 = dafut6Futureuse6;
        this.danltrNewletteronweb = danltrNewletteronweb;
        this.dapipaPersonalinfoprotectionact = dapipaPersonalinfoprotectionact;
        this.dapyinPaymentinstrument = dapyinPaymentinstrument;
        this.daoptiOptInReq=daoptiOptInReq;
        this.daoptfOptInFlag=daoptfOptInFlag;
        this.daopdtOptInDate=daopdtOptInDate;
        this.dascemSpnContbyEml=dascemSpnContbyEml;
        this.dascphSpnContbyPhn=dascemSpnContbyEml;
        this.dadavfAdrVerfdFlag=dadavfAdrVerfdFlag;
        this.dadlatAdrLatitude=dadlatAdrLatitude;
        this.dadlntAdrLongitude=dadlntAdrLongitude;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    // @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    // @Column(name = "DACTL_DISTRIBUTORCTL", nullable = false)
    public long getDactlDistributorctl() {
        return this.dactlDistributorctl;
    }

    public void setDactlDistributorctl(long dactlDistributorctl) {
        this.dactlDistributorctl = dactlDistributorctl;
    }

    // @Column(name = "DAPSWD_PASSWORD", nullable = false)
    public String getDapswdPassword() {
        return this.dapswdPassword;
    }

    public void setDapswdPassword(String dapswdPassword) {
        this.dapswdPassword = dapswdPassword;
    }

    // @Column(name = "DAEMAD_EMAILADDRESS", nullable = false)
    public String getDaemadEmailaddress() {
        return this.daemadEmailaddress;
    }

    public void setDaemadEmailaddress(String daemadEmailaddress) {
        this.daemadEmailaddress = daemadEmailaddress;
    }

    // @Column(name = "DAEBKN_BANKNAME")
    public String getDaebknBankname() {
        return this.daebknBankname;
    }

    public void setDaebknBankname(String daebknBankname) {
        this.daebknBankname = daebknBankname;
    }

    // @Column(name = "DABRNM_BRANCHNAME")
    public String getDabrnmBranchname() {
        return this.dabrnmBranchname;
    }

    public void setDabrnmBranchname(String dabrnmBranchname) {
        this.dabrnmBranchname = dabrnmBranchname;
    }

    // @Column(name = "DABRCD_BRANCHCODE")
    public Long getDabrcdBranchcode() {
        return this.dabrcdBranchcode;
    }

    public void setDabrcdBranchcode(Long dabrcdBranchcode) {
        this.dabrcdBranchcode = dabrcdBranchcode;
    }

    // @Column(name = "DAPHN1_PHONENUMBER")
    public Long getDaphn1Phonenumber() {
        return this.daphn1Phonenumber;
    }

    public void setDaphn1Phonenumber(Long daphn1Phonenumber) {
        this.daphn1Phonenumber = daphn1Phonenumber;
    }

    // @Column(name = "DAPHN2_PHONENUMBER")
    public Long getDaphn2Phonenumber() {
        return this.daphn2Phonenumber;
    }

    public void setDaphn2Phonenumber(Long daphn2Phonenumber) {
        this.daphn2Phonenumber = daphn2Phonenumber;
    }

    // @Column(name = "DABLOV_BNSLIMITOVERRIDE", length = 1)
    public String getDablovBnslimitoverride() {
        return this.dablovBnslimitoverride;
    }

    public void setDablovBnslimitoverride(String dablovBnslimitoverride) {
        this.dablovBnslimitoverride = dablovBnslimitoverride;
    }

    // @Column(name = "DAFUT1_VIPPRICING", length = 1)
    public String getDafut1Vippricing() {
        return this.dafut1Vippricing;
    }

    public void setDafut1Vippricing(String dafut1Vippricing) {
        this.dafut1Vippricing = dafut1Vippricing;
    }

    // @Column(name = "DAFUT2_25CCOVERRIDE", length = 1)
    public String getDafut225ccoverride() {
        return this.dafut225ccoverride;
    }

    public void setDafut225ccoverride(String dafut225ccoverride) {
        this.dafut225ccoverride = dafut225ccoverride;
    }

    // @Column(name = "DAUSER_CHANGEUSER", length = 15)
    public String getDauserChangeuser() {
        return this.dauserChangeuser;
    }

    public void setDauserChangeuser(String dauserChangeuser) {
        this.dauserChangeuser = dauserChangeuser;
    }

    // @Column(name = "DAPID_CHGPROGRAMID", length = 15)
    public String getDapidChgprogramid() {
        return this.dapidChgprogramid;
    }

    public void setDapidChgprogramid(String dapidChgprogramid) {
        this.dapidChgprogramid = dapidChgprogramid;
    }

    // @Column(name = "DAUPDT_CHANGEDATE", length = 15)
    public String getDaupdtChangedate() {
        return this.daupdtChangedate;
    }

    public void setDaupdtChangedate(String daupdtChangedate) {
        this.daupdtChangedate = daupdtChangedate;
    }

    // @Column(name = "DAUPTM_CHANGETIME", length = 15)
    public String getDauptmChangetime() {
        return this.dauptmChangetime;
    }

    public void setDauptmChangetime(String dauptmChangetime) {
        this.dauptmChangetime = dauptmChangetime;
    }

    // @Column(name = "DARCTP_BANKTYPECODE", length = 1)
    public String getDarctpBanktypecode() {
        return this.darctpBanktypecode;
    }

    public void setDarctpBanktypecode(String darctpBanktypecode) {
        this.darctpBanktypecode = darctpBanktypecode;
    }

    // @Column(name = "DATRNS_BANKRTGTRANSIT", length = 25)
    public String getDatrnsBankrtgtransit() {
        return this.datrnsBankrtgtransit;
    }

    public void setDatrnsBankrtgtransit(String datrnsBankrtgtransit) {
        this.datrnsBankrtgtransit = datrnsBankrtgtransit;
    }

    // @Column(name = "DAACT_BANKACCT", length = 25)
    public String getDaactBankacct() {
        return this.daactBankacct;
    }

    public void setDaactBankacct(String daactBankacct) {
        this.daactBankacct = daactBankacct;
    }

    // @Column(name = "DASWFT_SWIFTCODE", length = 25)
    public String getDaswftSwiftcode() {
        return this.daswftSwiftcode;
    }

    public void setDaswftSwiftcode(String daswftSwiftcode) {
        this.daswftSwiftcode = daswftSwiftcode;
    }

    // @Column(name = "DAPREN_PRENOTECODE", length = 1)
    public String getDaprenPrenotecode() {
        return this.daprenPrenotecode;
    }

    public void setDaprenPrenotecode(String daprenPrenotecode) {
        this.daprenPrenotecode = daprenPrenotecode;
    }

    // @Column(name = "DACKSV_CHKGORSVGSACCT", length = 1)
    public String getDacksvChkgorsvgsacct() {
        return this.dacksvChkgorsvgsacct;
    }

    public void setDacksvChkgorsvgsacct(String dacksvChkgorsvgsacct) {
        this.dacksvChkgorsvgsacct = dacksvChkgorsvgsacct;
    }

    // @Column(name = "DADUSR_DIRDEPCHGUSER", length = 25)
    public String getDadusrDirdepchguser() {
        return this.dadusrDirdepchguser;
    }

    public void setDadusrDirdepchguser(String dadusrDirdepchguser) {
        this.dadusrDirdepchguser = dadusrDirdepchguser;
    }

    // @Column(name = "DADPID_DIRDEPCHGPGMID", length = 25)
    public String getDadpidDirdepchgpgmid() {
        return this.dadpidDirdepchgpgmid;
    }

    public void setDadpidDirdepchgpgmid(String dadpidDirdepchgpgmid) {
        this.dadpidDirdepchgpgmid = dadpidDirdepchgpgmid;
    }

    // @Column(name = "DADUDT_DIRDEPCHGDATE", length = 15)
    public String getDadudtDirdepchgdate() {
        return this.dadudtDirdepchgdate;
    }

    public void setDadudtDirdepchgdate(String dadudtDirdepchgdate) {
        this.dadudtDirdepchgdate = dadudtDirdepchgdate;
    }

    // @Column(name = "DADUTM_DIRDEPCHGTIME", length = 15)
    public String getDadutmDirdepchgtime() {
        return this.dadutmDirdepchgtime;
    }

    public void setDadutmDirdepchgtime(String dadutmDirdepchgtime) {
        this.dadutmDirdepchgtime = dadutmDirdepchgtime;
    }

    // @Column(name = "DAOHCO_OVERRIDINGHOMECOUNTRY", length = 5)
    public String getDaohcoOverridinghomecountry() {
        return this.daohcoOverridinghomecountry;
    }

    public void setDaohcoOverridinghomecountry(String daohcoOverridinghomecountry) {
        this.daohcoOverridinghomecountry = daohcoOverridinghomecountry;
    }

    // @Column(name = "DAWEBR_WEBRECAP", length = 1)
    public String getDawebrWebrecap() {
        return this.dawebrWebrecap;
    }

    public void setDawebrWebrecap(String dawebrWebrecap) {
        this.dawebrWebrecap = dawebrWebrecap;
    }

    // @Column(name = "DADBDT_DISTBIRTHDATE", length = 15)
    public String getDadbdtDistbirthdate() {
        return this.dadbdtDistbirthdate;
    }

    public void setDadbdtDistbirthdate(String dadbdtDistbirthdate) {
        this.dadbdtDistbirthdate = dadbdtDistbirthdate;
    }

    // @Column(name = "DASBDT_SPOUBIRTHDATE", length = 15)
    public String getDasbdtSpoubirthdate() {
        return this.dasbdtSpoubirthdate;
    }

    public void setDasbdtSpoubirthdate(String dasbdtSpoubirthdate) {
        this.dasbdtSpoubirthdate = dasbdtSpoubirthdate;
    }

    // @Column(name = "DAMSTS_MARTIALSTATUS", length = 1)
    public String getDamstsMartialstatus() {
        return this.damstsMartialstatus;
    }

    public void setDamstsMartialstatus(String damstsMartialstatus) {
        this.damstsMartialstatus = damstsMartialstatus;
    }

    // @Column(name = "DALSPK_LANGUAGESPOKEN", length = 5)
    public String getDalspkLanguagespoken() {
        return this.dalspkLanguagespoken;
    }

    public void setDalspkLanguagespoken(String dalspkLanguagespoken) {
        this.dalspkLanguagespoken = dalspkLanguagespoken;
    }

    // @Column(name = "DAATR_APPLTRANSACTIONID")
    public Long getDaatrAppltransactionid() {
        return this.daatrAppltransactionid;
    }

    public void setDaatrAppltransactionid(Long daatrAppltransactionid) {
        this.daatrAppltransactionid = daatrAppltransactionid;
    }

    // @Column(name = "DANDPF_NDPPRICINGYN", length = 1)
    public String getDandpfNdppricingyn() {
        return this.dandpfNdppricingyn;
    }

    public void setDandpfNdppricingyn(String dandpfNdppricingyn) {
        this.dandpfNdppricingyn = dandpfNdppricingyn;
    }

    // @Column(name = "DABALF_BALANCEFACTOR", precision = 5, scale = 3)
    public BigDecimal getDabalfBalancefactor() {
        return this.dabalfBalancefactor;
    }

    public void setDabalfBalancefactor(BigDecimal dabalfBalancefactor) {
        this.dabalfBalancefactor = dabalfBalancefactor;
    }

    // @Column(name = "DAFUT3_FUTUREUSE3", precision = 9, scale = 3)
    public BigDecimal getDafut3Futureuse3() {
        return this.dafut3Futureuse3;
    }

    public void setDafut3Futureuse3(BigDecimal dafut3Futureuse3) {
        this.dafut3Futureuse3 = dafut3Futureuse3;
    }

    // @Column(name = "DAFUT4_FUTUREUSE4", length = 1)
    public String getDafut4Futureuse4() {
        return this.dafut4Futureuse4;
    }

    public void setDafut4Futureuse4(String dafut4Futureuse4) {
        this.dafut4Futureuse4 = dafut4Futureuse4;
    }

    // @Column(name = "DAFUT5_FUTUREUSE5", length = 1)
    public String getDafut5Futureuse5() {
        return this.dafut5Futureuse5;
    }

    public void setDafut5Futureuse5(String dafut5Futureuse5) {
        this.dafut5Futureuse5 = dafut5Futureuse5;
    }

    // @Column(name = "DAFUT6_FUTUREUSE6", length = 1)
    public String getDafut6Futureuse6() {
        return this.dafut6Futureuse6;
    }

    public void setDafut6Futureuse6(String dafut6Futureuse6) {
        this.dafut6Futureuse6 = dafut6Futureuse6;
    }

    // @Column(name = "DANLTR_NEWLETTERONWEB", length = 1)
    public String getDanltrNewletteronweb() {
        return this.danltrNewletteronweb;
    }

    public void setDanltrNewletteronweb(String danltrNewletteronweb) {
        this.danltrNewletteronweb = danltrNewletteronweb;
    }

    // @Column(name = "DAPIPA_PERSONALINFOPROTECTIONACT", length = 1)
    public String getDapipaPersonalinfoprotectionact() {
        return this.dapipaPersonalinfoprotectionact;
    }

    public void setDapipaPersonalinfoprotectionact(String dapipaPersonalinfoprotectionact) {
        this.dapipaPersonalinfoprotectionact = dapipaPersonalinfoprotectionact;
    }

    // @Column(name = "DAPYIN_PAYMENTINSTRUMENT", length = 1)
    public String getDapyinPaymentinstrument() {
        return this.dapyinPaymentinstrument;
    }

    public void setDapyinPaymentinstrument(String dapyinPaymentinstrument) {
        this.dapyinPaymentinstrument = dapyinPaymentinstrument;
    }

    // @Column(name="DAOPTI_OPTINREQ",length =1 )
    public String getDaoptiOptInReq() {
        return daoptiOptInReq;
    }

    public void setDaoptiOptInReq(String daoptiOptInReq) {
        this.daoptiOptInReq = daoptiOptInReq;
    }

    // @Column(name="DAOPTF_OPTINFLAG",length = 1)
    public String getDaoptfOptInFlag() {
        return daoptfOptInFlag;
    }

    public void setDaoptfOptInFlag(String daoptfOptInFlag) {
        this.daoptfOptInFlag = daoptfOptInFlag;
    }

    // @Column(name="DAOPDT_OPTINDATE",nullable = true,length = 10)
    public String getDaopdtOptInDate() {
        return daopdtOptInDate;
    }

    public void setDaopdtOptInDate(String daoptdOptInDate) {
        this.daopdtOptInDate = daoptdOptInDate;
    }

    // @Column(name="DASCEM_SPNCONTBYEML",length = 1)
    public String getDascemSpnContbyEml() {
        return dascemSpnContbyEml;
    }

    public void setDascemSpnContbyEml(String dascemSpnContbyEml) {
        this.dascemSpnContbyEml = dascemSpnContbyEml;
    }

    // @Column(name = "DASCPH_SPNCONTBYPHN",length = 1)
    public String getDascphSpnContbyPhn() {
        return dascphSpnContbyPhn;
    }

    public void setDascphSpnContbyPhn(String dascphSpnContbyPhn) {
        this.dascphSpnContbyPhn = dascphSpnContbyPhn;
    }

    // @Column(name="DADAVF_ADRVERFDFLAG",length = 1)
    public String getDadavfAdrVerfdFlag() {
        return dadavfAdrVerfdFlag;
    }

    public void setDadavfAdrVerfdFlag(String dadavfAdrVerfdFlag) {
        this.dadavfAdrVerfdFlag = dadavfAdrVerfdFlag;
    }

    // @Column(name="DADLAT_ADRLATITUDE",nullable = true,precision =11,scale = 9)
    public BigDecimal getDadlatAdrLatitude() {
        return dadlatAdrLatitude;
    }

    public void setDadlatAdrLatitude(BigDecimal dadlatAdrLatitude) {
        this.dadlatAdrLatitude = dadlatAdrLatitude;
    }

    // @Column(name="DADLNT_ADRLONGITUDE",nullable = true,precision = 11,scale = 9)
    public BigDecimal getDadlntAdrLongitude() {
        return dadlntAdrLongitude;
    }

    public void setDadlntAdrLongitude(BigDecimal dadlntAdrLongitude) {
        this.dadlntAdrLongitude = dadlntAdrLongitude;
    }

    public DsainpDistAddInfo copy() {
        DsainpDistAddInfo d = new DsainpDistAddInfo();
        d.dactlDistributorctl = dactlDistributorctl;
        d.dapswdPassword = dapswdPassword;
        d.daemadEmailaddress = daemadEmailaddress;
        d.daebknBankname = daebknBankname;
        d.dabrnmBranchname = dabrnmBranchname;
        d.dabrcdBranchcode = dabrcdBranchcode;
        d.daphn1Phonenumber = daphn1Phonenumber;
        d.daphn2Phonenumber = daphn2Phonenumber;
        d.dablovBnslimitoverride = dablovBnslimitoverride;
        d.dafut1Vippricing = dafut1Vippricing;
        d.dafut225ccoverride = dafut225ccoverride;
        d.dauserChangeuser = dauserChangeuser;
        d.dapidChgprogramid = dapidChgprogramid;
        d.daupdtChangedate = daupdtChangedate;
        d.dauptmChangetime = dauptmChangetime;
        d.darctpBanktypecode = darctpBanktypecode;
        d.datrnsBankrtgtransit = datrnsBankrtgtransit;
        d.daactBankacct = daactBankacct;
        d.daswftSwiftcode = daswftSwiftcode;
        d.daprenPrenotecode = daprenPrenotecode;
        d.dacksvChkgorsvgsacct = dacksvChkgorsvgsacct;
        d.dadusrDirdepchguser = dadusrDirdepchguser;
        d.dadpidDirdepchgpgmid = dadpidDirdepchgpgmid;
        d.dadudtDirdepchgdate = dadudtDirdepchgdate;
        d.dadutmDirdepchgtime = dadutmDirdepchgtime;
        d.daohcoOverridinghomecountry = daohcoOverridinghomecountry;
        d.dawebrWebrecap = dawebrWebrecap;
        d.dadbdtDistbirthdate = dadbdtDistbirthdate;
        d.dasbdtSpoubirthdate = dasbdtSpoubirthdate;
        d.damstsMartialstatus = damstsMartialstatus;
        d.dalspkLanguagespoken = dalspkLanguagespoken;
        d.daatrAppltransactionid = daatrAppltransactionid;
        d.dandpfNdppricingyn = dandpfNdppricingyn;
        d.dabalfBalancefactor = dabalfBalancefactor;
        d.dafut3Futureuse3 = dafut3Futureuse3;
        d.dafut4Futureuse4 = dafut4Futureuse4;
        d.dafut5Futureuse5 = dafut5Futureuse5;
        d.dafut6Futureuse6 = dafut6Futureuse6;
        d.danltrNewletteronweb = danltrNewletteronweb;
        d.dapipaPersonalinfoprotectionact = dapipaPersonalinfoprotectionact;
        d.dapyinPaymentinstrument = dapyinPaymentinstrument;
        d.daoptiOptInReq=daoptiOptInReq;
        d.daoptfOptInFlag=daoptfOptInFlag;
        d.daopdtOptInDate=daopdtOptInDate;
        d.dascemSpnContbyEml=dascemSpnContbyEml;
        d.dascphSpnContbyPhn=dascemSpnContbyEml;
        d.dadavfAdrVerfdFlag=dadavfAdrVerfdFlag;
        d.dadlatAdrLatitude=dadlatAdrLatitude;
        d.dadlntAdrLongitude=dadlntAdrLongitude;
        return d;
    }

    @Override
    public String toString() {
        return "DsainpDistAddInfo{" +
                "id=" + id +
                ", dactlDistributorctl=" + dactlDistributorctl +
                ", dapswdPassword='" + dapswdPassword + '\'' +
                ", daemadEmailaddress='" + daemadEmailaddress + '\'' +
                ", daebknBankname='" + daebknBankname + '\'' +
                ", dabrnmBranchname='" + dabrnmBranchname + '\'' +
                ", dabrcdBranchcode=" + dabrcdBranchcode +
                ", daphn1Phonenumber=" + daphn1Phonenumber +
                ", daphn2Phonenumber=" + daphn2Phonenumber +
                ", dablovBnslimitoverride='" + dablovBnslimitoverride + '\'' +
                ", dafut1Vippricing='" + dafut1Vippricing + '\'' +
                ", dafut225ccoverride='" + dafut225ccoverride + '\'' +
                ", dauserChangeuser='" + dauserChangeuser + '\'' +
                ", dapidChgprogramid='" + dapidChgprogramid + '\'' +
                ", daupdtChangedate='" + daupdtChangedate + '\'' +
                ", dauptmChangetime='" + dauptmChangetime + '\'' +
                ", darctpBanktypecode='" + darctpBanktypecode + '\'' +
                ", datrnsBankrtgtransit='" + datrnsBankrtgtransit + '\'' +
                ", daactBankacct='" + daactBankacct + '\'' +
                ", daswftSwiftcode='" + daswftSwiftcode + '\'' +
                ", daprenPrenotecode='" + daprenPrenotecode + '\'' +
                ", dacksvChkgorsvgsacct='" + dacksvChkgorsvgsacct + '\'' +
                ", dadusrDirdepchguser='" + dadusrDirdepchguser + '\'' +
                ", dadpidDirdepchgpgmid='" + dadpidDirdepchgpgmid + '\'' +
                ", dadudtDirdepchgdate='" + dadudtDirdepchgdate + '\'' +
                ", dadutmDirdepchgtime='" + dadutmDirdepchgtime + '\'' +
                ", daohcoOverridinghomecountry='" + daohcoOverridinghomecountry + '\'' +
                ", dawebrWebrecap='" + dawebrWebrecap + '\'' +
                ", dadbdtDistbirthdate='" + dadbdtDistbirthdate + '\'' +
                ", dasbdtSpoubirthdate='" + dasbdtSpoubirthdate + '\'' +
                ", damstsMartialstatus='" + damstsMartialstatus + '\'' +
                ", dalspkLanguagespoken='" + dalspkLanguagespoken + '\'' +
                ", daatrAppltransactionid=" + daatrAppltransactionid +
                ", dandpfNdppricingyn='" + dandpfNdppricingyn + '\'' +
                ", dabalfBalancefactor=" + dabalfBalancefactor +
                ", dafut3Futureuse3=" + dafut3Futureuse3 +
                ", dafut4Futureuse4='" + dafut4Futureuse4 + '\'' +
                ", dafut5Futureuse5='" + dafut5Futureuse5 + '\'' +
                ", dafut6Futureuse6='" + dafut6Futureuse6 + '\'' +
                ", danltrNewletteronweb='" + danltrNewletteronweb + '\'' +
                ", dapipaPersonalinfoprotectionact='" + dapipaPersonalinfoprotectionact + '\'' +
                ", dapyinPaymentinstrument='" + dapyinPaymentinstrument + '\'' +
                ", daoptiOptInReq='" + daoptiOptInReq + '\'' +
                ", daoptfOptInFlag='" + daoptfOptInFlag + '\'' +
                ", daopdtOptInDate='" + daopdtOptInDate + '\'' +
                ", dascemSpnContbyEml='" + dascemSpnContbyEml + '\'' +
                ", dascphSpnContbyPhn='" + dascphSpnContbyPhn + '\'' +
                ", dadavfAdrVerfdFlag='" + dadavfAdrVerfdFlag + '\'' +
                ", dadlatAdrLatitude=" + dadlatAdrLatitude +
                ", dadlntAdrLongitude=" + dadlntAdrLongitude +
                '}';
    }
}
