package com.ns.dataloading.entity;
// Generated 6 Feb, 2019 3:59:49 PM by Hibernate Tools 5.1.10.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * DsdtrpFlptojdetrans generated by hbm2java
 */
@Entity
@Table(name = "DSDTRP_FlpToJdeTrans")
public class DsdtrpFlptojdetrans implements java.io.Serializable {

    private Long id;
    private String dtaorcAddOrChange;
    private Long dtctlDistributorControl;
    private String dtchgcChangeCode;

    public DsdtrpFlptojdetrans() {
    }

    public DsdtrpFlptojdetrans(String dtaorcAddOrChange, Long dtctlDistributorControl, String dtchgcChangeCode) {
        this.dtaorcAddOrChange = dtaorcAddOrChange;
        this.dtctlDistributorControl = dtctlDistributorControl;
        this.dtchgcChangeCode = dtchgcChangeCode;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "DTAORC_AddOrChange")
    public String getDtaorcAddOrChange() {
        return this.dtaorcAddOrChange;
    }

    public void setDtaorcAddOrChange(String dtaorcAddOrChange) {
        this.dtaorcAddOrChange = dtaorcAddOrChange;
    }

    @Column(name = "DTCTL_DistributorControl")
    public Long getDtctlDistributorControl() {
        return this.dtctlDistributorControl;
    }

    public void setDtctlDistributorControl(Long dtctlDistributorControl) {
        this.dtctlDistributorControl = dtctlDistributorControl;
    }

    @Column(name = "DTCHGC_ChangeCode")
    public String getDtchgcChangeCode() {
        return this.dtchgcChangeCode;
    }

    public void setDtchgcChangeCode(String dtchgcChangeCode) {
        this.dtchgcChangeCode = dtchgcChangeCode;
    }

}
